### ISSUE TITLE
Bot Sometimes Freezes on Startup

### ISSUE THREAD

**Issue by MTS11648** [LCN-Dev/GoogleBot#174]
#### Brief description of the issue:
The bot freezes when I start it.
#### What happened?:
The bot freezes when I start it.
#### What _should_ have happened?:
The bot shouldn't freeze when I start it.
#### Steps to reproduce:
1) Start the bot.
2) Watch it freeze.
#### Additional info:
I think this might have something to do with the file check, maybe if the file server is down it freezes.

**Comment by MTS11648** [comment]
Marked as severe because after restarting the bot multiple times, it still won't work.

**Comment by MTS11648** [comment]
Yep, theory about the file server is confirmed, takes at **least** a few minutes to show a message box about failure.

**Comment by SpadesNeil** [comment]
To disable the file check intentionally, go into the debug folder, find the fileServer.txt, and either remove it or change its contents. It will then skip the file check.

Knocking this down to minor since it's just an inconvenience and doesn't interfere with the bot's operation now that we know this.

**Comment by MTS11648** [comment]
Closed because I now know the cause of the issue and it can be fixed easily.
