### ISSUE TITLE
New TCPA Rebuttals aren't their own task, cannot fire properly.

### ISSUE THREAD

**Issue by MTS11648** [LCN-Dev/GoogleBot#196]
#### Brief description of the issue:
I did not make the function awaitable, so Cheryl will begin to rebuttal the TCPA but just say, "Sorry can you repeat that please?" instead.
#### What _should_ have happened?:
Cheryl should rebuttal the TCPA properly.
#### Steps to reproduce:
1) Get to TCPA.
2) Say "No."
3) Watch Cheryl fail to properly rebuttal you.
#### Additional info:
I'm at school so I can't fix this right now, putting this here so a) someone else can get to it first or b) I remember to fix it

**Comment by NicksAccount** [comment]
Get to class slacker

**Comment by NicksAccount** [comment]
On the TCPA we're losing some people because Cheryl will say 'and that's okay with you?" and if the person says anything but yes (which they do sometimes, just yes like "yeah. i don't care") she shoots that "and thats okay with you correct?" again and it turns people off a lot. If it detects speech after the "and that's okay..." question, could it stop there? And if there's a question, could it shoot the rebuttal for that question?
Example:
"What's the company?"
"LCN stands for Loud Cloud Nine we're trying to help you.....etc"

**Comment by SpadesNeil** [comment]
If the person said yes, the call is going to be sent to us as a successful call. We shouldn't be losing people at that point in the call.

**Comment by NicksAccount** [comment]
Yes, but "You can revoke your consent at anytime", therefore if they say yes, and she says, "And that's okay with you?" again and they change their minds, (which is what i meant by that), the lead is bad. But, it's not a major issue.

**Comment by SpadesNeil** [comment]
I've never seen that happen but that's awfully irritating.
